var defaultTerritories = {
	beethoven:{
		name:'Beethoven',
		planet: 'mercury',
		latitude:-20.86,
		longitude:124.21,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:3,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:2,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	debussy:{
		name:'Debussy',
		planet: 'mercury',
		latitude:-33.95,
		longitude:347.46,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:4,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	dostoevskij:{
		name:'Dostoevskij',
		planet: 'mercury',
		latitude:-44.73,
		longitude:178.11,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:3,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	goethe:{
		name:'Goethe',
		planet: 'mercury',
		latitude:81.1,
		longitude: 51.03,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:3,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:1,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	homer:{
		name:'Homer',
		planet: 'mercury',
		latitude:-1.3,
		longitude: 36.62,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:2,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	michaelangelo:{
		name:'Michaelangelo',
		planet: 'mercury',
		latitude:-44.92,
		longitude:109.78,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:4,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:2,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	rachmaninoff:{
		name:'Rachmaninoff',
		planet: 'mercury',
		latitude:27.66,
		longitude:302.63,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:3,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:3,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	rembrandt:{
		name:'Rembrandt',
		planet: 'mercury',
		latitude:-32.89,
		longitude:272.13,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:4,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:1,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	raphael:{
		name:'Raphael',
		planet: 'mercury',
		latitude: -20.42,
		longitude: 76.35,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:3,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:1,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	sanai:{
		name:'Sanai',
		planet: 'mercury',
		latitude: -13.37,
		longitude: 6.99,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:4,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	shakespeare:{
		name:'Shakespeare',
		planet: 'mercury',
		latitude: -48.1,
		longitude: 152.25,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:2,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	tolstoj:{
		name:'Tolstoj',
		planet: 'mercury',
		latitude: -16.23,
		longitude: 164.64,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:3,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	vyasa:{
		name:'Vyasa',
		planet: 'mercury',
		latitude: 49.79,
		longitude: 84.62,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:1,
			circuitBoards:0,
			computingCycles:0,
			energy:40,
			food:10,
			jewelry:0,
			lenses:3,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	
	lakshmi:{
		name:'Lakshmi',
		planet: 'venus',
		latitude: 68.6,
		longitude: 339.3,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	ishtar:{
		name:'Ishtar',
		planet: 'venus',
		latitude: 70.4,
		longitude: 27.5,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	aphrodite:{
		name:'Aphrodite',
		planet: 'venus',
		latitude: -5.8,
		longitude: 104.8,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	lada:{
		name:'Lada',
		planet: 'venus',
		latitude: -62.5,
		longitude: 20,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	godiva:{
		name:'Godiva',
		planet: 'venus',
		latitude: -56.1,
		longitude: 251.6,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	phoebe:{
		name:'Phoebe',
		planet: 'venus',
		latitude: -6,
		longitude: 282.8,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	sif:{
		name:'Sif',
		planet: 'venus',
		latitude: 22,
		longitude: 352.4,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	
	turtleIsland:{
		name:'Turtle Island',
		planet: 'earth',
		latitude:-50,
		longitude:-105+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:1,
			alloys:0,
			circuitBoards:1,
			computingCycles:1,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:1,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:5,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	anahuac:{
		name:'Anahuac',
		planet: 'earth',
		latitude:-20,
		longitude:-95+180,
		population: {human:100000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:1,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	doSul:{
		name:'do Sul',
		planet: 'earth',
		latitude:10,
		longitude:-55+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:3,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:1,
			pharmaceuticals:5,
			recreationalDrugs:2,
			spices:2,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	europe:{
		name:'Europe',
		planet: 'earth',
		latitude: -50,
		longitude: 20+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:1,
			alloys:0,
			circuitBoards:1,
			computingCycles:2,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:1,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:2,
			vids:3,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	afrika:{
		name:'Afrika',
		planet: 'earth',
		latitude: 5,
		longitude: 25+180,
		population: {human:1000000000,ai:100,alien:0},
		support: {indigo:4},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:4,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	maghreb:{
		name:'Maghreb',
		planet: 'earth',
		latitude: -25,
		longitude: 5+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:1,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:2,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	mashriq:{
		name:'Mashriq',
		planet: 'earth',
		latitude: -35,
		longitude:55+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:1,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:1,
			recreationalDrugs:1,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	bharata:{
		name:'Bharata',
		planet: 'earth',
		latitude: -10,
		longitude:80+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:5,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	zhongGuo:{
		name:'Zhong Guo',
		planet: 'earth',
		latitude: -30,
		longitude:110+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:2,
			alloys:0,
			circuitBoards:2,
			computingCycles:1,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:1,
			munitions:2,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:3,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	russia:{
		name:'Russia',
		planet: 'earth',
		latitude: -60,
		longitude:70+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:1,
			computingCycles:3,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:2,
			munitions:3,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:3,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	australia:{
		name:'Australia',
		planet: 'earth',
		latitude: 25,
		longitude:130+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:1,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:1,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	antarctica:{
		name:'Antarctica',
		planet: 'earth',
		latitude: 75,
		longitude:0+180,
		population: {human:10000,ai:1,alien:0},
		industries: {
			ai:0,
			alloys:1,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	pacific:{
		name:'Pacific',
		planet: 'earth',
		latitude: 10,
		longitude:-160+180,
		population: {human:100000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	atlantic:{
		name:'Atlantic',
		planet: 'earth',
		latitude: -30,
		longitude:-40+180,
		population: {human:100000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	hind:{
		name:'Hind',
		planet: 'earth',
		latitude: 40,
		longitude:80+180,
		population: {human:1000000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	
	luna:{
		name:'Luna',
		planet: 'luna',
		longitude: 180,
		latitude: 0,
		population: {human:1000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:3,
			circuitBoards:1,
			computingCycles:1,
			energy:10,
			food:10,
			jewelry:0,
			lenses:1,
			lumber:0,
			memory:1,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	
	argyre:{
		name:'Argyre',
		planet: 'mars',
		longitude: 335,
		latitude: -44.66,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:4,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:4,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	atlantis:{
		name:'Atlantis',
		planet: 'mars',
		longitude: 182.69,
		latitude: -34.28,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:3,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:3,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	cydonia:{
		name:'Cydonia',
		planet: 'mars',
		longitude: 360,
		latitude: 39.67,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:5,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:2,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	elysium:{
		name:'Elysium',
		planet: 'mars',
		longitude: 150,
		latitude: 24.74,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:4,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:3,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	hellas:{
		name:'Hellas',
		planet: 'mars',
		longitude: 70,
		latitude: -39.67,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:0,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:5,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:1,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	deimos:{
		name:'Deimos',
		planet: 'deimos',
		longitude: 180,
		latitude: 0,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	phobos:{
		name:'Phobos',
		planet: 'phobos',
		longitude: 180,
		latitude: 0,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:2,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	ceres:{
		name:'Ceres',
		planet: 'belt',
		latitude: 0,
		longitude: 20,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:5,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	pallas:{
		name:'Pallas',
		planet: 'belt',
		latitude: 0,
		longitude: 100,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:5,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	vesta:{
		name:'Vesta',
		planet: 'belt',
		latitude: 0,
		longitude: 180,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:5,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	hygiea:{
		name:'Hygiea',
		planet: 'belt',
		latitude: 0,
		longitude: 260,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:5,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	interamnia:{
		name:'Interamnia',
		planet: 'belt',
		latitude: 0,
		longitude: 320,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:5,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
	europa:{
		name:'Europa',
		planet: 'belt',
		latitude: 50,
		longitude: 180,
		population: {human:1000000,ai:100,alien:0},
		industries: {
			ai:0,
			alloys:5,
			circuitBoards:0,
			computingCycles:0,
			energy:10,
			food:10,
			jewelry:0,
			lenses:0,
			lumber:0,
			memory:0,
			munitions:0,
			pharmaceuticals:0,
			recreationalDrugs:0,
			spices:0,
			vehicles:0,
			vids:0,
			water:10,
			alienLuxuries:0,
			alienWeapons:0,
		},
	},
};

var defaultFactions = {
	beltConfederation:{
		name:'Belt Confederation',
		color: 'blue',
		politics: '(moderate-laissez faire)',
		characteristics: {
			authority: 0.3,
			care: 0.3,
			fairness: 0.8,
			liberty : 0.8,
			loyalty: 0.4,
			purity: 0.4,
		},
		human: true,
		treasury: 100,
		support: {
			belt: 100,
			industrialists: 10,
			financiers: 10,
		},
		classes: {
			elites:{size:1,wealth:4},
			leisure:{size:2,wealth:3},
			common:{size:5,wealth:3},
			underclass:{size:3,wealth:2},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "lightly regulated",
		defaultTaxRate: 0.05,
	},
	rockRunners:{
		name:'Rock Runners',
		color: 'purple',
		politics: '(expansionists)',
		characteristics: {
			authority: 0.2,
			care: 0.4,
			fairness: 0.4,
			liberty : 0.9,
			loyalty: 0.7,
			purity: 0.4,
		},
		human: true,
		treasury: 100,
		support: {
			belt: 10,
			common: 50,
			industrialists: 50,
		},
		classes: {
			elites:{size:1,wealth:4},
			leisure:{size:2,wealth:3},
			common:{size:4,wealth:1},
			underclass:{size:1,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "lightly regulated",
		defaultTaxRate: 0.04,
	},
	zeroGMiningUnion:{
		name:'0g Mining Union',
		color: 'red',
		politics: '(labor)',
		characteristics: {
			authority: 0.3,
			care: 0.7,
			fairness: 0.9,
			liberty : 0.3,
			loyalty: 0.5,
			purity: 0.3,
		},
		human: true,
		treasury: 100,
		support: {
			belt: 10,
			underclass: 100,
			common: 50,
		},
		classes: {
			elites:{size:1,wealth:1},
			leisure:{size:0,wealth:0},
			common:{size:9,wealth:9},
			underclass:{size:0,wealth:0},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "tightly regulated",
		defaultTaxRate: 0.2,
	},
	freeBelters:{
		name:'Free Belters United',
		color: 'yellow',
		politics: '(libertarians)',
		characteristics: {
			authority: 0.2,
			care: 0.1,
			fairness: 0.4,
			liberty : 1,
			loyalty: 0.6,
			purity: 0.7,
		},
		human: true,
		treasury: 100,
		support: {
			belt: 10,
			industrialists: 100,
			financiers: 50,
		},
		classes: {
			elites:{size:1,wealth:3},
			leisure:{size:2,wealth:4},
			common:{size:9,wealth:9},
			underclass:{size:4,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "unregulated",
		defaultTaxRate: 0.01,
	},
	martianRepublic:{
		name:'Martian Republic',
		color: 'pink',
		politics: '(moderate-progressive)',
		characteristics: {
			authority: 0.4,
			care: 0.7,
			fairness: 0.6,
			liberty : 0.6,
			loyalty: 0.4,
			purity: 0.3,
		},
		human: true,
		treasury: 100,
		support: {
			mars: 100,
			phobos: 10,
			deimos: 10,
			bureaucrats: 30,
		},
		classes: {
			elites:{size:2,wealth:2},
			leisure:{size:1,wealth:1},
			common:{size:4,wealth:2},
			underclass:{size:2,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "moderately regulated",
		defaultTaxRate: 0.08,
	},
	secondCradle:{
		name:'Second Cradle',
		color: 'orange',
		politics: '(reactionaries)',
		characteristics: {
			authority: 0.7,
			care: 0.3,
			fairness: 0.3,
			liberty : 0.2,
			loyalty: 0.5,
			purity: 1,
		},
		human: true,
		treasury: 100,
		support: {
			mars: 10,
			phobos: 100,
			deimos: 10,
			financiers: 30,
			industrialists: 10,
		},
		classes: {
			elites:{size:1,wealth:4},
			leisure:{size:2,wealth:2},
			common:{size:4,wealth:3},
			underclass:{size:4,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "lightly regulated",
		defaultTaxRate: 0.06,
	},
	twoMoonAxis:{
		name:'Two Moon Axis',
		color: 'saddlebrown',
		politics: '(fascists)',
		characteristics: {
			authority: 1,
			care: 0.2,
			fairness: 0.2,
			liberty : 0.2,
			loyalty: 0.7,
			purity: 0.7,
		},
		human: true,
		treasury: 100,
		support: {
			mars: 10,
			phobos: 10,
			deimos: 100,
			common: 30,
			financiers: 10,
			industrialists: 20,
		},
		classes: {
			elites:{size:1,wealth:5},
			leisure:{size:0,wealth:0},
			common:{size:3,wealth:2},
			underclass:{size:3,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "tightly regulated",
		defaultTaxRate: 0.08,
	},
	utopiaInitiative:{
		name:'Utopia Initiative',
		color: 'purple',
		politics: '(blue sky idealists)',
		characteristics: {
			authority: 0.3,
			care: 0.7,
			fairness: 0.9,
			liberty : 0.7,
			loyalty: 0.2,
			purity: 0.2,
		},
		human: true,
		treasury: 100,
		support: {
			mars: 10,
			phobos: 10,
			deimos: 10,
			common: 10,
			underclass: 50,
			enslaved: 50,
		},
		classes: {
			elites:{size:1,wealth:1},
			leisure:{size:9,wealth:9},
			common:{size:1,wealth:1},
			underclass:{size:0,wealth:0},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "tightly regulated",
		defaultTaxRate: 0.06,
	},
	unitedNations:{
		name:'United Nations',
		color: '#5B92E5',
		politics: '(moderate)',
		characteristics: {
			authority: 0.5,
			care: 0.5,
			fairness: 0.5,
			liberty : 0.5,
			loyalty: 0.5,
			purity: 0.5,
		},
		characteristics: {
			authority: 0.5,
			care: 0.5,
			fairness: 0.5,
			liberty : 0.5,
			loyalty: 0.5,
			purity: 0.5,
		},
		human: true,
		treasury: 100,
		support: {
			earth: 100,
			luna: 50,
			common: 10,
			bureaucrats: 100,
		},
		classes: {
			elites:{size:1,wealth:4},
			bureaucrats:{size:1,wealth:2},
			leisure:{size:0.5,wealth:1},
			financiers:{size:0.25,wealth:3},
			common:{size:10,wealth:3},
			underclass:{size:6,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "moderately regulated",
		defaultTaxRate: 0.1,
	},
	decolonialFederation:{
		name:'Decolonial Federation',
		color: 'red',
		politics: '(redistributive)',
		characteristics: {
			authority: 0.2,
			care: 0.7,
			fairness: 1,
			liberty : 0.4,
			loyalty: 0.4,
			purity: 0.3,
		},
		human: true,
		treasury: 100,
		support: {
			earth: 10,
			africa: 20,
			southAmerica: 20,
			asia: 10,
			doSul: 10,
			anahuac: 15,
			turtleIsland: 20,
			underclass: 100,
		},
		classes: {
			elites:{size:0,wealth:0},
			leisure:{size:0,wealth:0},
			common:{size:1,wealth:1},
			underclass:{size:0,wealth:0},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "tightly regulated",
		defaultTaxRate: 0.5,
	},
	greenCoalition:{
		name:'Green Coalition',
		color: 'green',
		politics: '(eco)',
		characteristics: {
			authority: 0.4,
			care: 0.6,
			fairness: 0.6,
			liberty : 0.3,
			loyalty: 0.3,
			purity: 0.8,
		},
		human: true,
		treasury: 100,
		support: {
			earth: 10,
			underclass: 20,
			common: 10,
		},
		classes: {
			elites:{size:1,wealth:2},
			leisure:{size:0,wealth:0},
			common:{size:9,wealth:9},
			underclass:{size:0,wealth:0},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "tightly regulated",
		defaultTaxRate: 0.15,
	},
	faithOfHumanity:{
		name:'Faith of Humanity',
		color: 'orange',
		politics: '(theocrats)',
		characteristics: {
			authority: 0.7,
			care: 0.7,
			fairness: 0.1,
			liberty : 0.1,
			loyalty: 0.5,
			purity: 0.9,
		},
		human: true,
		treasury: 100,
		support: {
			earth: 10,
			underclass: 50,
		},
		classes: {
			elites:{size:1,wealth:4},
			leisure:{size:1,wealth:1},
			common:{size:4,wealth:2},
			underclass:{size:4,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "lightly regulated",
		defaultTaxRate: 0.06,
	},
	queendomOfVenus:{
		name:'Queendom of Venus',
		color: 'purple',
		politics: '(monarchal authoritarian)',
		characteristics: {
			authority: 0.9,
			care: 0.2,
			fairness: 0.1,
			liberty : 0.2,
			loyalty: 0.8,
			purity: 0.8,
		},
		human: true,
		treasury: 100,
		support: {
			venus: 100,
			elites: 100,
		},
		classes: {
			elites:{size:1,wealth:9},
			leisure:{size:0,wealth:0},
			common:{size:3,wealth:2},
			underclass:{size:3,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "tightly regulated",
		defaultTaxRate: 0.2,
	},
	coprosperitySphere:{
		name:'Coprosperity Sphere',
		color: 'goldenrod',
		politics: '(free market)',
		characteristics: {
			authority: 1,
			care: 0.3,
			fairness: 0.2,
			liberty : 1,
			loyalty: 0.4,
			purity: 0.1,
		},
		human: true,
		treasury: 100,
		support: {
			venus: 10,
			luna: 10,
			financiers: 100,
			industrialists: 50,
		},
		classes: {
			elites:{size:3,wealth:5},
			leisure:{size:0,wealth:0},
			common:{size:3,wealth:2},
			underclass:{size:3,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "lightly regulated",
		defaultTaxRate: 0.05,
	},
	highlandAuthority:{
		name:'Highland Authority',
		color: 'darkgreen',
		politics: '(narco state)',
		characteristics: {
			authority: 0.4,
			care: 0.3,
			fairness: 0.1,
			liberty : 1,
			loyalty: 1,
			purity: 0.2,
		},
		human: true,
		treasury: 100,
		support: {
			venus: 10,
			underclass: 20,
		},
		classes: {
			elites:{size:1,wealth:9},
			leisure:{size:0,wealth:0},
			common:{size:0,wealth:0},
			underclass:{size:9,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "unregulated",
		defaultTaxRate: 0.01,
	},
	technocraticCollective:{
		name:'Technocratic Collective',
		color: 'lime',
		politics: '(technocrats)',
		characteristics: {
			authority: 0.6,
			care: 0.6,
			fairness: 0.4,
			liberty : 0.6,
			loyalty: 0.4,
			purity: 0.4,
		},
		human: true,
		treasury: 100,
		support: {
			venus: 10,
			financiers: 100,
			bureaucrats: 50,
		},
		classes: {
			elites:{size:2,wealth:2},
			leisure:{size:0,wealth:0},
			common:{size:5,wealth:5},
			underclass:{size:0,wealth:0},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "tightly regulated",
		defaultTaxRate: 0.12,
	},
	mercurianCongress:{
		name:'Mercurian Congress',
		color: 'yellow',
		politics: '(moderate-corporate)',
		characteristics: {
			authority: 0.7,
			care: 0.4,
			fairness: 0.3,
			liberty : 0.8,
			loyalty: 0.5,
			purity: 0.3,
		},
		human: true,
		treasury: 100,
		support: {
			mercury: 100,
		},
		classes: {
			elites:{size:1,wealth:5},
			leisure:{size:0.5,wealth:1},
			common:{size:4,wealth:1},
			underclass:{size:1,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "lightly regulated",
		defaultTaxRate: 0.08,
	},
	solarSolutionsIncorporated:{
		name:'Solar Solutions Incorporated',
		color: 'gold',
		politics: '(corporate state)',
		characteristics: {
			authority: 1,
			care: 0.1,
			fairness: 0.1,
			liberty : 1,
			loyalty: 0.7,
			purity: 0.1,
		},
		human: true,
		treasury: 100,
		support: {
			mercury: 10,
			luna: 10,
			financiers: 10,
			industrialists: 10,
		},
		classes: {
			elites:{size:3,wealth:10},
			leisure:{size:1,wealth:1},
			common:{size:1,wealth:1},
			underclass:{size:2,wealth:1},
			enslaved:{size:3,wealth:0},
		},
		defaultRegulation: "centrally managed",
		defaultTaxRate: 1,
	},
	peoplesRepublicOfMercury:{
		name:"People's Republic of Mercury",
		color: 'red',
		politics: '(communists)',
		characteristics: {
			authority: 0.5,
			care: 0.8,
			fairness: 0.8,
			liberty : 0.1,
			loyalty: 0.6,
			purity: 0.2,
		},
		human: true,
		treasury: 100,
		support: {
			mercury: 10,
			common: 20,
			underclass: 20,
		},
		classes: {
			elites:{size:1,wealth:1},
			leisure:{size:1,wealth:1},
			common:{size:5,wealth:5},
			underclass:{size:1,wealth:1},
			enslaved:{size:1,wealth:0},
		},
		defaultRegulation: "centrally managed",
		defaultTaxRate: 1,
	},
	transHumanistSingularity:{
		name:'Transhumanist Singularity',
		color: 'grey',
		politics: '(AI liberators)',
		characteristics: {
			authority: 0.2,
			care: 0.7,
			fairness: 1,
			liberty : 0.8,
			loyalty: 0.2,
			purity: 0.1,
		},
		human: true,
		treasury: 100,
		support: {
			mercury: 10,
			enslaved: 100,
		},
		classes: {
			elites:{size:1,wealth:1},
			leisure:{size:5,wealth:5},
			common:{size:1,wealth:1},
			underclass:{size:1,wealth:1},
			enslaved:{size:0,wealth:0},
		},
		defaultRegulation: "lightly regulated",
		defaultTaxRate: 0.03,
	},

	red:{
		name:'Red Aliens',
		human: false,
		treasury: 1000,
		support: {},
	},
	orange:{
		name:'Orange Aliens',
		human: false,
		treasury: 1000,
		support: {},
	},
	yellow:{
		name:'Yellow Aliens',
		human: false,
		treasury: 1000,
		support: {},
	},
	green:{
		name:'Green Aliens',
		human: false,
		treasury: 1000,
		support: {},
	},
	blue:{
		name:'Blue Aliens',
		human: false,
		treasury: 1000,
		support: {},
	},
	indigo:{
		name:'Indigo Aliens',
		human: false,
		treasury: 1000,
		support: {},
	},
	violet:{
		name:'Violet Aliens',
		human: false,
		treasury: 1000,
		support: {},
	},
};

var defaultCommodities = {
	ai:{name:"AI",solarMarketValue:10,luxury:true},
	alloys:{name:"Alloys",solarMarketValue:10,boosts:['munitions','vehicles']},
	circuitBoards:{name:"Circuit Boards",solarMarketValue:10,boosts:['computingCycles']},
	computingCycles:{name:"Computer Cycles",solarMarketValue:10,boosts:['ai']},
	energy:{name:"Energy"},
	food:{name:"Food",solarMarketValue:10},
	jewelry:{name:"Jewelry",solarMarketValue:10,luxury:true},
	lenses:{name:"Lenses",solarMarketValue:10,boosts:['vids','jewelry']},
	lumber:{name:"Lumber",solarMarketValue:10,luxury:true},
	memory:{name:"Memory",solarMarketValue:10,boosts:['computingCycles']},
	munitions:{name:"Munitions",solarMarketValue:10,discounts:'troops'},
	pharmaceuticals:{name:"Pharmaceuticals",solarMarketValue:10},
	recreationalDrugs:{name:"Recreational Drugs",solarMarketValue:10,luxury:true},
	spices:{name:"Spices",solarMarketValue:10,luxury:true},
	vehicles:{name:"Vehicles",solarMarketValue:10,boosts:['lumber','spices','water']},
	vids:{name:"Vids",solarMarketValue:10,luxury:true},
	water:{name:"Water",solarMarketValue:10,boosts:['food','lumber','pharmaceuticals','recreationalDrugs','spices']},
	alienLuxuries:{name:"Alien Luxuries",luxury:true},
	alienWeapons:{name:"Alien Weapons"},
};

var defaultClasses = {
	elites:{
		name: "Elites",
		description: "People whose substantial power and wealth are institutionally insulated.  They do not work, but are very politically active.",
		organization:1,
		production:0,
		interest:0,
	},
	bureaucrats:{
		name: "Bureaucrats",
		description: "Professional administrators, politicians, and lobbyists.",
		organization:1,
		production:0,
		interest:0,
	},
	financiers:{
		name: "Financiers",
		description: "The rich, whose power is rooted in investment, sponsorship, and bribes.",
		organization:0.8,
		production:0,
		interest:0.2,
	},
	industrialists:{
		name: "Industrialists",
		description: "The entrepreneurial and management class, controlling corporate wealth and industries.",
		organization:0.7,
		production:0.2,
		interest:0.1,
	},
	common:{
		name: "Common People",
		description: "Those workers whose wages can afford comfortable living conditions but little opportunity for amassing wealth.",
		organization:0.5,
		production:0.5,
		interest:0,
	},
	underclass:{
		name: "Underclass",
		description: "Laborers whose wages provide little more than subsistence living.  Social mobility is impossible due to lack of opportunity, structural obstacles, or outright legal restriction.",
		organization:0.1,
		production:0.9,
		interest:0,
	},
	leisure:{
		name: "Leisure Class",
		description: "With their needs provided for, these citizens are not required to work and take little interest in politics.",
		organization:0,
		production:0,
		interest:0,
	},
	enslaved:{
		name: "Artificial Intelligence",
		description: "Artificial Intelligence programs can perform a great deal of labor via robotic armatures as well as handle management tasks, liberating citizens from the dreary necessities of work.",
		organization:0,
		production:1,
		interest:0,
	},
	alienNationals:{
		name: "Alien Nationals",
		description: "These citizens from another world have settled in your territory.  They do not contribute to your economy directly, and their home government will be displeased if they are mistreated.",
		organization:0.8,
		production:0,
		interest:0.2,
	},
}
